// src/shared/components/CommandPalette.tsx
"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import {
  SIDEBAR_SECTIONS,
  getSectionItems,
  HIDDEN_SIDEBAR_ITEMS_SETTING_KEY,
  normalizeHiddenSidebarItems,
} from "@/shared/constants/sidebarVisibility";

interface CommandPaletteProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function CommandPalette({ isOpen, onClose }: CommandPaletteProps) {
  if (!isOpen) return null;
  return <CommandPaletteDialog onClose={onClose} />;
}

interface PaletteItem {
  id: string;
  href: string;
  icon: string;
  label: string;
  subtitle?: string;
  external: boolean;
}

function CommandPaletteDialog({ onClose }: { onClose: () => void }) {
  const router = useRouter();
  const t = useTranslations("sidebar");
  const inputRef = useRef<HTMLInputElement>(null);
  const listRef = useRef<HTMLUListElement>(null);
  const [query, setQuery] = useState("");
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [hiddenItems, setHiddenItems] = useState<Set<string>>(new Set());

  useEffect(() => {
    const ctrl = new AbortController();
    fetch("/api/settings", { signal: ctrl.signal })
      .then((res) => res.json())
      .then((data) => {
        setHiddenItems(
          new Set(normalizeHiddenSidebarItems(data?.[HIDDEN_SIDEBAR_ITEMS_SETTING_KEY]))
        );
      })
      .catch(() => {
        // ignore aborts and fetch failures; palette still works with empty hidden set
      });
    return () => ctrl.abort();
  }, []);

  useEffect(() => {
    const id = setTimeout(() => inputRef.current?.focus(), 30);
    return () => clearTimeout(id);
  }, []);

  const safeTranslate = useCallback(
    (key: string, fallback: string) => {
      try {
        return t(key);
      } catch {
        return fallback;
      }
    },
    [t]
  );

  const allItems = useMemo<PaletteItem[]>(
    () =>
      SIDEBAR_SECTIONS.flatMap((section) =>
        getSectionItems(section)
          .filter((item) => !hiddenItems.has(item.id))
          .map((item) => ({
            id: item.id,
            href: item.href,
            icon: item.icon,
            label: safeTranslate(item.i18nKey, item.id),
            subtitle: item.subtitleKey ? safeTranslate(item.subtitleKey, "") : undefined,
            external: item.external ?? false,
          }))
      ),
    [hiddenItems, safeTranslate]
  );

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return allItems;
    return allItems.filter(
      (item) => item.label.toLowerCase().includes(q) || item.subtitle?.toLowerCase().includes(q)
    );
  }, [allItems, query]);

  const handleNavigate = useCallback(
    (href: string, external: boolean) => {
      onClose();
      if (external) {
        window.open(href, "_blank", "noopener,noreferrer");
      } else {
        router.push(href);
      }
    },
    [onClose, router]
  );

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        onClose();
        return;
      }
      if (e.key === "ArrowDown") {
        e.preventDefault();
        setSelectedIndex((prev) => (prev + 1) % Math.max(1, filtered.length));
      } else if (e.key === "ArrowUp") {
        e.preventDefault();
        setSelectedIndex(
          (prev) => (prev - 1 + Math.max(1, filtered.length)) % Math.max(1, filtered.length)
        );
      } else if (e.key === "Enter") {
        e.preventDefault();
        const item = filtered[selectedIndex];
        if (item) {
          handleNavigate(item.href, item.external);
        }
      }
    };
    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [filtered, selectedIndex, onClose, handleNavigate]);

  useEffect(() => {
    const list = listRef.current;
    if (!list) return;
    const el = list.children[selectedIndex] as HTMLElement | undefined;
    el?.scrollIntoView({ block: "nearest" });
  }, [selectedIndex]);

  return (
    <div className="fixed inset-0 z-[60] flex items-start justify-center pt-[15vh] px-4">
      <div
        className="absolute inset-0 bg-black/40 backdrop-blur-sm"
        onClick={onClose}
        aria-hidden="true"
      />
      <div
        className="relative w-full max-w-lg bg-bg border border-black/10 dark:border-white/10 rounded-2xl shadow-2xl overflow-hidden"
        role="dialog"
        aria-modal="true"
        aria-label="Command palette"
      >
        <div className="flex items-center gap-3 px-4 py-3 border-b border-black/5 dark:border-white/5">
          <span className="material-symbols-outlined text-[18px] text-text-muted shrink-0">
            search
          </span>
          <input
            ref={inputRef}
            type="text"
            className="flex-1 bg-transparent text-text placeholder:text-text-muted outline-none text-sm"
            placeholder="Go to..."
            value={query}
            onChange={(e) => {
              setQuery(e.target.value);
              setSelectedIndex(0);
            }}
            autoComplete="off"
            spellCheck={false}
          />
          {query && (
            <button
              className="text-text-muted hover:text-text transition-colors"
              onClick={() => {
                setQuery("");
                setSelectedIndex(0);
              }}
              tabIndex={-1}
              aria-label="Clear search"
            >
              <span className="material-symbols-outlined text-[16px]">close</span>
            </button>
          )}
          <kbd className="hidden sm:inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded text-[10px] font-mono bg-black/5 dark:bg-white/5 text-text-muted border border-black/10 dark:border-white/10 shrink-0">
            Esc
          </kbd>
        </div>

        {filtered.length > 0 ? (
          <ul
            ref={listRef}
            className="py-1.5 max-h-80 overflow-y-auto custom-scrollbar"
            role="listbox"
          >
            {filtered.map((item, idx) => (
              <li key={item.id} role="option" aria-selected={idx === selectedIndex}>
                <button
                  className={`w-full flex items-center gap-3 px-4 py-2.5 text-left transition-colors ${
                    idx === selectedIndex
                      ? "bg-accent/10 text-accent"
                      : "text-text hover:bg-black/5 dark:hover:bg-white/5"
                  }`}
                  onClick={() => handleNavigate(item.href, item.external)}
                  onMouseEnter={() => setSelectedIndex(idx)}
                >
                  <span
                    className={`material-symbols-outlined text-[18px] shrink-0 ${
                      idx === selectedIndex ? "text-accent" : "text-text-muted"
                    }`}
                  >
                    {item.icon}
                  </span>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium truncate">{item.label}</p>
                    {item.subtitle && (
                      <p
                        className={`text-xs truncate ${
                          idx === selectedIndex ? "text-accent/70" : "text-text-muted"
                        }`}
                      >
                        {item.subtitle}
                      </p>
                    )}
                  </div>
                  {item.external && (
                    <span className="material-symbols-outlined text-[14px] text-text-muted shrink-0">
                      open_in_new
                    </span>
                  )}
                </button>
              </li>
            ))}
          </ul>
        ) : (
          <div className="py-10 text-center text-text-muted text-sm">No results</div>
        )}

        <div className="flex items-center gap-4 px-4 py-2 border-t border-black/5 dark:border-white/5 text-[11px] text-text-muted">
          <span className="flex items-center gap-1">
            <kbd className="px-1 py-0.5 rounded bg-black/5 dark:bg-white/5 border border-black/10 dark:border-white/10 font-mono">
              ↑↓
            </kbd>
            navigate
          </span>
          <span className="flex items-center gap-1">
            <kbd className="px-1 py-0.5 rounded bg-black/5 dark:bg-white/5 border border-black/10 dark:border-white/10 font-mono">
              ↵
            </kbd>
            open
          </span>
          <span className="flex items-center gap-1">
            <kbd className="px-1 py-0.5 rounded bg-black/5 dark:bg-white/5 border border-black/10 dark:border-white/10 font-mono">
              Esc
            </kbd>
            close
          </span>
        </div>
      </div>
    </div>
  );
}

// apps/web/src/lib/components/foundation/CommandPalette.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';

  type Action = { id: string; label: string; hint?: string; run: () => void };

  let open = $state(false);
  let query = $state('');
  let inputEl: HTMLInputElement | null = $state(null);
  let selectedIdx = $state(0);

  const actions: Action[] = [
    { id: 'go-dashboard', label: 'Go to Dashboard', hint: '/dashboard', run: () => nav('/dashboard') },
    { id: 'go-providers', label: 'Go to Providers', hint: '/dashboard/providers', run: () => nav('/dashboard/providers') },
    { id: 'go-usage', label: 'Go to Usage', hint: '/dashboard/usage', run: () => nav('/dashboard/usage') },
    { id: 'go-health', label: 'Go to Health', hint: '/dashboard/health', run: () => nav('/dashboard/health') },
    { id: 'go-settings', label: 'Go to Settings', hint: '/dashboard/settings/general', run: () => nav('/dashboard/settings/general') },
    { id: 'go-security', label: 'Go to Security', hint: '/dashboard/security', run: () => nav('/dashboard/security') },
    { id: 'go-keys', label: 'Go to API Keys', hint: '/dashboard/keys', run: () => nav('/dashboard/keys') },
    { id: 'go-combos', label: 'Go to Combos', hint: '/dashboard/combos', run: () => nav('/dashboard/combos') },
    { id: 'theme-light', label: 'Theme: Light', run: () => setTheme('light') },
    { id: 'theme-dark', label: 'Theme: Dark', run: () => setTheme('dark') },
    { id: 'theme-auto', label: 'Theme: Auto', run: () => setTheme('auto') },
    { id: 'reload', label: 'Reload current page', run: () => location.reload() },
  ];

  const filtered = $derived(
    query
      ? actions.filter((a) => `${a.label} ${a.hint ?? ''}`.toLowerCase().includes(query.toLowerCase()))
      : actions
  );

  function nav(href: string) { open = false; location.href = href; }
  function setTheme(t: 'auto' | 'light' | 'dark') {
    document.documentElement.classList.toggle('dark', t === 'dark' || (t === 'auto' && matchMedia('(prefers-color-scheme: dark)').matches));
    localStorage.setItem('argismonitor-theme', t);
    open = false;
  }

  function onKeydown(e: KeyboardEvent) {
    if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
      e.preventDefault();
      open = !open;
      query = '';
      selectedIdx = 0;
      queueMicrotask(() => inputEl?.focus());
    } else if (e.key === 'Escape' && open) {
      open = false;
    } else if (open && e.key === 'Enter' && filtered[selectedIdx]) {
      filtered[selectedIdx].run();
    } else if (open && e.key === 'ArrowDown') {
      e.preventDefault();
      selectedIdx = Math.min(selectedIdx + 1, filtered.length - 1);
    } else if (open && e.key === 'ArrowUp') {
      e.preventDefault();
      selectedIdx = Math.max(selectedIdx - 1, 0);
    }
  }

  onMount(() => {
    window.addEventListener('keydown', onKeydown);
  });
  onDestroy(() => {
    if (typeof window !== 'undefined') window.removeEventListener('keydown', onKeydown);
  });
</script>

{#if open}
  <div class="fixed inset-0 z-50 bg-black/40 flex items-start justify-center pt-24" onclick={() => open = false} role="presentation">
    <div class="bg-white rounded-lg shadow-2xl w-full max-w-xl mx-4 overflow-hidden" onclick={(e) => e.stopPropagation()} role="dialog">
      <input
        bind:this={inputEl}
        bind:value={query}
        type="search"
        placeholder="Type a command or search..."
        class="w-full px-4 py-3 text-base border-b border-gray-200 focus:outline-none"
      />
      <ul class="max-h-80 overflow-y-auto">
        {#each filtered as a, i (a.id)}
          <li>
            <button
              type="button"
              onclick={() => a.run()}
              onmouseenter={() => selectedIdx = i}
              class="w-full text-left px-4 py-2 hover:bg-gray-100 {i === selectedIdx ? 'bg-gray-100' : ''}"
            >
              <div class="text-sm font-medium text-gray-900">{a.label}</div>
              {#if a.hint}<div class="text-xs text-gray-500 font-mono">{a.hint}</div>{/if}
            </button>
          </li>
        {/each}
        {#if filtered.length === 0}
          <li class="px-4 py-3 text-sm text-gray-500">No matches</li>
        {/if}
      </ul>
      <div class="px-4 py-2 text-xs text-gray-400 border-t border-gray-100 flex gap-3">
        <span><kbd class="px-1.5 py-0.5 bg-gray-100 rounded">{'<Mod>'}</kbd>+<kbd class="px-1.5 py-0.5 bg-gray-100 rounded">K</kbd> open</span>
        <span><kbd class="px-1.5 py-0.5 bg-gray-100 rounded">↑↓</kbd> navigate</span>
        <span><kbd class="px-1.5 py-0.5 bg-gray-100 rounded">↵</kbd> run</span>
        <span><kbd class="px-1.5 py-0.5 bg-gray-100 rounded">Esc</kbd> close</span>
      </div>
    </div>
  </div>
{/if}
